Source/PRFacAppWF/Controllers/TouchListController.cs
namespace PRFacAppWF.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using PRFacAppWF.CodeHelpers;
    using System.Data;
    using Entities.Touches;
    using Entities;
    using System.Linq;

    [HandleJsonExceptionAttribute]
    [Authorize]
    public class TouchListController : BaseController
    {
        private readonly WarehouseTouches oWarehouseTouches;

        public TouchListController()
        {
            if (oWarehouseTouches == null)
                oWarehouseTouches = new WarehouseTouches();
        }


        public ActionResult Index()
        {
            GlobalSettings gs = new GlobalSettings();

            TouchListFilterCriteria FC = new TouchListFilterCriteria
            {
                StartDate = gs.FAWTSearchStartDate,
                EndDate = gs.FAWTSearchEndDate,
                StatusTypes = oWarehouseTouches.GetWHTStatusList()
            };

            return View(FC);
        }

        [HttpPost]
        public JsonResult SearchTouches(TouchListFilterCriteria FilterCriteria)
        {
            ResultSet<WATouchInfo> lstTI = new ResultSet<WATouchInfo>();
            AjaxResponse<ResultSet<WATouchInfo>> response = new AjaxResponse<ResultSet<WATouchInfo>>();
            try
            {
                FilterCriteria.LocationCode = CurrentSiteInfo.LocationCode;

                lstTI.rows = oWarehouseTouches.GetWATouchs(FilterCriteria);
                lstTI.total = lstTI.rows.Count;
                lstTI.page = 1;
                lstTI.records = lstTI.rows.Count();

                List<WATouchInfo> finalTouchList = new List<WATouchInfo>();

                response.data = lstTI;
                response.success = true;
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                response.success = false;
                response.message = ex.Message;
            }

            #region Added by Sohan - for "Invalid JSON primitive" unexpected Error when no data. 
            if (!response.success && response.message.Contains("Invalid JSON primitive"))
            {
                response.message = "Error - No Data Found !!";
                response.success = true;
                response.data = new ResultSet<WATouchInfo>() { rows = new List<WATouchInfo>(), page = 1, total = 0, records = 0 };
            }
            #endregion

            return new JsonResult { Data = response, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = int.MaxValue };
        }

        public JsonResult SaveEditTouchInfo(WATouchInfo touchInfo)
        {
            var response = new AjaxResponse<object>();
            try
            {
                oWarehouseTouches.HandleUpdateWarehouseTouchInfo(touchInfo, CurrentUser.ID);
                response.success = true;
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                response.success = false;
                response.message = ex.Message;
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EditTouchInfo(string touchType, int statusID, DateTime touchScheduleDate)
        {
            var response = new AjaxResponse<List<FAWTTouchActions>>();
            response.success = true;
            response.message = "";
            try
            {
                response.data = oWarehouseTouches.GetActionsByTouchType(touchType, statusID, touchScheduleDate, Convert.ToInt32(CurrentSiteInfo.GlobalSiteNum));
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                response.message = ex.Message;
                response.success = false;
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidateUnitName(string unitName)
        {
            var response = new AjaxResponse<bool>();
            response.success = true;
            try
            {
                response.data = oWarehouseTouches.IsValidUnitName(unitName);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                response.message = ex.Message;
                response.success = false;
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTouchHistory(int QORID, string TouchType, int SeqNumber)
        {
            var response = new AjaxResponse<object>();
            response.success = true;
            response.message = "";
            try
            {
                var touchHistory = oWarehouseTouches.GetTouchHistory(QORID, TouchType, SeqNumber);
                response.data = new { touchHistory = RenderPartialView("~/Views/TouchList/partial/_touchHistoryBody.cshtml", touchHistory.AsEnumerable()) };
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                response.message = ex.Message;
                response.success = false;
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #region BOL

        public JsonResult GetBOLURL(string qorid)
        {
            return null;
        }
        #endregion


    }
}

Source/PRFacAppWF/Views/TouchList/partial/_FilterWATouches.cshtml
@model PRFacAppWF.Entities.Touches.TouchListFilterCriteria

@using (Html.BeginForm("SearchTouches", "TouchList", null, System.Web.Mvc.FormMethod.Post, new { id = "WarehouseTouchFilterCriteria", onsubmit = "" }))
{
    <div class="pivot-item">
        <div class="bg-grey-newfilter">
            <div class="tiltepanel" style="margin-left:20px">
                <h4 class="title-h4 width100prcnt">
                    <span id="hShowHide" style="cursor:pointer">Search Criteria</span>           
                    <span class="ui-icon ui-icon-circle-triangle-n float-right" style="cursor: pointer;" id="showHideButton">&nbsp;</span>
                </h4>
                <div class="clearfix"></div>
                <ul class="form-list form-list-watouches" style="margin-top: 0%;">
                    <li class="width30prcnt ">
                        <span class="label-form">Start Date</span>
                        <span class="value">
                            <div class="input-control text ">
                                <input type="text" value="@Model.StartDate.ToString("MM/dd/yyyy")" name="StartDate" id="StartDate" readonly="readonly" title="Select start date to search records." style="margin-right: 0px; width: 80%;" />
                                <img src="../Images/calendar-Icon.gif" id="StartDateIcon" />
                            </div>
                        </span>
                    </li>
                    <li class="width30prcnt ">
                        <span class="label-form">End Date</span>
                        <span class="value">
                            <div class="input-control text">
                                <input type="text" value="@Model.EndDate.ToString("MM/dd/yyyy")" name="EndDate" id="EndDate" readonly="readonly" title="Select end date to search records." style="margin-right: 0px; width: 80%;" />
                                <img src="../Images/calendar-Icon.gif" id="EndDateIcon" />
                            </div>
                        </span>
                    </li>
                    <li class="width30prcnt ">
                        <span class="label-form">Status</span>
                        <span class="value">
                            <div class="input-control text">
                                <select class="" name="Status" id="Status" title="Select status to search records.">
                                    <option value="-1">-- All--</option>
                                    @foreach (var item in Model.StatusTypes)
                                    {
                                        <option value="@item.TouchStatusID" @(item.TouchStatusID == 0 ? "selected='selected'" : string.Empty)>@item.StatusName</option>
                                    }
                                </select>
                            </div>
                        </span>
                    </li>
                    <li class="width100prcnt">
                        <ul class="form-list form-list-watouches" style="margin-top: 0%;">                            
                            <li class="width30prcnt ">
                                <span class="label-form">First Name</span>
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="text" name="FirstName" id="FirstName" title="Enter first name to search records." style="margin-right: 0px; width: 80%;" />
                                    </div>
                                </span>
                            </li>                            
                            <li class="width30prcnt ">
                                <span class="label-form">Last Name</span>
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="text" name="LastName" id="LastName" title="Enter last name to search records." style="margin-right: 0px; width: 80%;" />
                                    </div>
                                </span>
                            </li>
                            <li class="width30prcnt ">
                                <span class="label-form">Touch Type</span>
                                <span class="value">
                                    <div class="input-control text">
                                        <select class="" name="TouchType" id="TouchType" title="Select touch type to search records.">
                                            <option value="-1">--Select--</option>
                                            <option value="4">All</option>
                                            <option value="6">Custom</option>
                                            <option value="7">Needs Action</option>
                                            <option value="5">None</option>
                                            <option value="3">Stage</option>
                                            <option value="2">Transportation</option>
                                            <option value="1">Warehouse</option>
                                        </select>
                                    </div>
                                </span>
                            </li>
                        </ul>
                    </li>
                    <li class="width100prcnt">
                        <ul class="form-list form-list-watouches" style="margin-top: 0%;">                            
                            <li class="width30prcnt ">
                                <span class="label-form">Number (Order, Units, STARS)</span>
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="text" name="TouchIdentificationNumber" id="TouchIdentificationNumber" title="Enter number to search records." style="margin-right: 0px; width: 80%;" />
                                    </div>
                                </span>
                            </li>                            
                            <li class="width30prcnt">
                                <span class="value">
                                    <div class="input-control text">
                                        @*<input type="checkbox" name="IsShowCompletedTouches" id="IsShowCompletedTouches" title="Check to view completed touches." /><span class="wstouch-touchtype">Show Completed Touches</span>
                                        *@<br />
                                        <input type="checkbox" name="IsShowPriorNotCompletedTouches" id="IsShowPriorNotCompletedTouches" checked="checked" title="Check to view prior touches." /><span class="wstouch-touchtype">Prior Warehouse Touches Not Completed</span>
                                    </div>
                                </span>
                            </li>
                            <li class="width36prcnt">
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="checkbox" name="IsDETouches" id="IsDETouches" title="Check to view DE touches." data-TouchType="DE" class="chkTouchType"/><span class="wstouch-touchtype">DE</span>
                                        <input type="checkbox" name="IsRFTouches" id="IsRFTouches" title="Check to view RF touches." data-TouchType="RF" class="chkTouchType"/><span class="wstouch-touchtype">RF</span>
                                        <input type="checkbox" name="IsCCToches" id="IsCCToches" title="Check to view CC touches." data-TouchType="CC" class="chkTouchType"/><span class="wstouch-touchtype">CC</span>
                                        <input type="checkbox" name="IsDFTouches" id="IsDFTouches" title="Check to view DF touches." data-TouchType="DF" class="chkTouchType"/><span class="wstouch-touchtype">DF</span>
                                        <input type="checkbox" name="IsRETouches" id="IsRETouches" title="Check to view RE touches." data-TouchType="RE" class="chkTouchType"/><span class="wstouch-touchtype">RE</span>
                                        <br />
                                        <input type="checkbox" name="IsWATouches" id="IsWATouches" title="Check to view DE touches." data-TouchType="WA" class="chkTouchType"/><span class="wstouch-touchtype">WA</span>
                                        <input type="checkbox" name="IsLDMOutTouches" id="IsLDMOutTouches" title="Check to view LDM Out touches." data-TouchType="TO" class="chkTouchType"/><span class="wstouch-touchtype">LDM Out</span>
                                        <input type="checkbox" name="IsLDMInTouches" id="IsLDMInTouches" title="Check to view LDM In touches." data-TouchType="TI" class="chkTouchType"/><span class="wstouch-touchtype">LDM In</span>
                                        <input type="checkbox" name="IsIBOTouches" id="IsIBOTouches" title="Check to view IBO touches." data-TouchType="IBO" class="chkTouchType"/><span class="wstouch-touchtype">IBO</span>
                                        <input type="checkbox" name="IsOBOTouches" id="IsOBOTouches" title="Check to view OBO touches." data-TouchType="OBO" class="chkTouchType"/><span class="wstouch-touchtype">OBO</span>
                                    </div>
                                </span>
                            </li>
                        </ul>
                    </li>
                    <li class="width100prcnt">
                        <div class="button-panel">
                            <input type="submit" value="Search" id="btnSearch" title="Click to search." />
                            <input type="reset" value="Reset" id="btnReset" title="Click to reset page." />
                            <input type="submit" value="Print" id="btnPrint" title="Click here to print." />
                            @*<input type="submit" hidden value="Print PDF" id="btnPrintPDF" title="Click here to print." />*@
                        </div>
                    </li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
}

Source/PRFacAppWF/Views/TouchList/partial/_editTouchDetails.cshtml
<div id="edittouchInfo">
    <ul>
        <li><a href="#edit_Touch_Info">Edit Touch</a></li>
        <li><a href="#touchHistory">View Touch History</a></li>
    </ul>
    <div id="edit_Touch_Info">
                @Html.Partial("~/Views/TouchList/partial/_editTouchInfo.cshtml")
        <div class="clear"></div>
    </div>
    <div id="touchHistory">
        @Html.Partial("~/Views/TouchList/partial/_touchHistory.cshtml")
        <div class="clear"></div>
    </div>
</div>

Source/PRFacAppWF/Views/TouchList/partial/_editTouchInfo.cshtml
<div>
    <input type="hidden" id="hfTouchKey" />
    <ul class="form-list form-list-new watouch-edit-form">
        <li class="wa-touch-completed-sl width100prcnt" id="smtTouchStatusCompleted">
            <p>This touch has been completed in Salesforce. You cannot change touch status.</p>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">Customer: </span>
            <span id="CustomerName" class="value">
            </span>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">Order: </span>
            <span id="OrderNumber" class="value">
            </span>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">Status: </span>
            <span id="lblStatusName" class="value">
            </span>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">TouchType: </span>
            <span id="SpanTouchType" class="value">
            </span>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">Action: </span>
            <span class="value">
                <div class="input-control text ">
                    @*BELOW DROP DOWN WILL POPULATE ON EDIT CLICK ACTION, BECAUSE STATUS MAY WARRAY BASED ON TOUCH TYPE AND TOUCH SCHEDULED DATE*@
                    <select name="Status" id="ddEditAction" title="Select action to update.">
                        <option value="-1">--Select--</option>
                    </select>
                </div>
            </span>
        </li>
        <li class="width48prcnt ">
            <span class="label-form">Previous Action: </span>
            <span id="SpanTouchPreviousAction" class="value" style="padding-bottom: 32px;">
            </span>
        </li>
        <li class="width48prcnt hide" id="unitNumberTextField" style="margin-top: 0.5%">
            <span class="label-form">Unit Name</span>
            <span class="value">
                <div class="input-control text">
                    <input type="text" name="UnitNumber" id="UnitNumber" title="Enter unit number." />
                    <input type="hidden" id="hdnUnitNumberValidationReq" value="false" />
                </div>
            </span>
        </li>
        <li class="width100prcnt">
            <span class="label-form">Notes: </span>
            <span class="value comments">
                <div class="input-control text">
                    <textarea id="Notes" name="Notes"></textarea>
                </div>
            </span>
        </li>
    </ul>
</div>

Source/PRFacAppWF/Views/TouchList/partial/_touchHistory.cshtml
<div class="driver-schedule-driverrover-list">
    <table class="tblTouchHistory new-fixed-header">
        <thead>
            <tr>
                <th class="width22prcnt">
                    Status Name
                </th>
                <th class="width22prcnt">
                    Action Name
                </th>
                <th class="width22prcnt">
                    Comments
                </th>
                <th class="width22prcnt">
                    Created Date
                </th>
            </tr>
        </thead>
        <tbody id="tBodyTouchHistory"></tbody>
    </table>
</div>

Source/PRFacAppWF/Views/TouchList/partial/_touchHistoryBody.cshtml
@model  IEnumerable<PRFacAppWF.Entities.Touches.WATouchInfoHistory>

@if (Model.Count() > 0)
{
    foreach (var touchInfo in Model)
    {
        <tr>
            <td>
                @touchInfo.DispStatusName
            </td>
            <td class="width12prcnt">
                @touchInfo.ActionName
            </td>
            <td class="width12prcnt">
                @touchInfo.Comments
            </td>
            <td class="width12prcnt">
                @touchInfo.HistCreatedDate.ToString("MM/dd/yyyy hh:mm tt")
            </td>
        </tr>
    }
}
else
{
    <tr>
        <td colspan="4">
           There is no history available to the touch.
        </td>       
    </tr>
}