Source/PRFacAppWF/Controllers/ApplicationSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PRFacAppWF.CodeHelpers;
using PRFacAppWF.models;
using PRFacAppWF.Repository.Services;

namespace PRFacAppWF.Controllers
{
    [HandleJsonExceptionAttribute]
    [Authorize]
    public class ApplicationSettingsController : BaseController
    {
        private readonly IPRSService prsService;

        public ApplicationSettingsController()
        {
            if (this.prsService == null)
                this.prsService = new PRSService();
        }

        /// <summary>
        /// Application settings index page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            this.ViewBag.AllApplicationSettings = this.prsService.GetAllApplicationSettings();

            return View();
        }

        public PartialViewResult SearchApplicationSettings(DateTime Date, string SortCol = null, string SortDir = null)
        {
            List<ApplicationSettings> lstAS = new List<ApplicationSettings>();
            try
            {
                SortCol = SortCol == "" ? "FacilityName" : SortCol;
                SortDir = SortDir == "" ? "ASC" : SortDir;
                lstAS = this.prsService.GetApplicationSettingsList(Date, SortCol, SortDir);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
            }

            return PartialView("partial/_listApplicationSetting", lstAS);
        }

        public ActionResult GetApplicationSettingsList(string sidx, string sord, int page, int rows, string SettingName)
        {
            try
            {
                var varSettingResults = this.prsService.SearchApplicationSettingsList(SettingName);
                int totalCount = varSettingResults.Count();
                var sortedResults = FilterApplicationSettingsGrid(varSettingResults, sidx, sord, page, rows);
                var pageSize = 10;
                var totalRecords = totalCount;
                var totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageSize);

                var jsonData = new
                {
                    total = totalPages,
                    page = page,
                    records = totalRecords,
                    rows = (from lst in sortedResults
                            select new
                            {
                                i = lst.CAPApplicationParameterId,
                                cell = new string[]
                                {
                                    lst.CAPApplicationParameterId.ToString(),

                                    ///As per the Eric feedback, display time values in 12 hours format
                                    (lst.ValueUnit.ToString().Equals("time", StringComparison.OrdinalIgnoreCase) ? (DateTime.Parse(DateTime.Now.ToShortDateString() + " " + lst.ApplicationValue)).ToString("h:mm tt") : lst.ApplicationValue),
                                    lst.Startdate.HasValue ? lst.Startdate.Value.ToShortDateString():"",
                                    lst.Enddate.HasValue ? lst.Enddate.Value.ToShortDateString():"",
                                    lst.ValueUnit.ToString(),
                                    lst.ApplicationParameter.ToString()
                                }
                            }).ToArray()
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);

                var jsonData = new
                {
                    total = 0,
                    page = 0,
                    records = 0,
                    rows = new string[0]
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult UpdateApplicationSettingsRecords(string SettingName)
        {
            ViewBag.SettingName = SettingName;
            return View();
        }

        [HttpPost]
        public JsonResult UpdateApplicationSettingsRecords(FormCollection formCollection)
        {
            DateTime? endDate = null;
            string ApplicationValue = "";
            bool isNullEnddate = false;
            string result = string.Empty;
            string errMsg = string.Empty;
            bool success = true;
            try
            {
                string Settingname = formCollection["hidSettingname"].ToString();
                DateTime startDate = Convert.ToDateTime(formCollection["Startdate"]);
                ApplicationValue = formCollection["ApplicationValue"].ToString();

                ///Saving time should be 24 hour format bcz this value is beeing used by Capcity system. For now dont want to disturb it.
                if (Settingname.Equals("Facility_AM_End_Time", StringComparison.OrdinalIgnoreCase) || Settingname.Equals("FacilityAMTime", StringComparison.OrdinalIgnoreCase) || Settingname.Equals("FacilityPMTime", StringComparison.OrdinalIgnoreCase))
                {
                    ApplicationValue = (DateTime.Parse(DateTime.Now.ToShortDateString() + " " + ApplicationValue)).ToString("HH:mm");
                }

                isNullEnddate = Convert.ToBoolean(formCollection["hidNullEndDate"]);
                if (!isNullEnddate)
                    endDate = Convert.ToDateTime(formCollection["Enddate"]);
                string lstAS = this.prsService.UpdateApplicationSettingsValues(CurrentUser.ID, Settingname, startDate, endDate, ApplicationValue, isNullEnddate);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                success = false;
                errMsg = ex.Message;
            }

            var retJSON = new
            {
                success = success,
                error = errMsg
            };
            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }

        private IEnumerable<ApplicationSettings> FilterApplicationSettingsGrid(IEnumerable<ApplicationSettings> data, string sidx, string sord, int page, int rows)
        {

            int skiprows = (page - 1) * rows;
            ////Since in the UI we are displaying CapacityDate column as CapacityDateDisp.
            sidx = sidx == "" ? "Startdate" : sidx;
            if (sord == "desc")
                data = data.OrderByDescending(a => a.GetType().GetProperty(sidx).GetValue(a, null)).Skip(skiprows).Take(rows);
            else
                data = data.OrderBy(a => a.GetType().GetProperty(sidx).GetValue(a, null)).Skip(skiprows).Take(rows);

            return data;
        }
    }
}

Source/PRFacAppWF/Controllers/TruckStatusController.cs
namespace PRFacAppWF.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Script.Serialization;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using PRFacAppWF.CodeHelpers;
    using PRFacAppWF.models;
    using PRFacAppWF.Repository.Services;
    using PR.LocalLogisticsSolution.Interfaces;
    using PR.Entities;
    using System.Data;

    public class TruckStatusController : BaseController
    {
        private readonly IPRSService prsService;
        private IUserService _userService = null;
        private ITouchService _touchService = null;

        public TruckStatusController(IUserService userService, ITouchService touchService)
        {
            if (this.prsService == null)
                this.prsService = new PRSService();

            _userService = userService;
            _touchService = touchService;
        }


        public ActionResult Index()
        {
            TruckStatusDetails truckStatusDetails = new TruckStatusDetails();
            EditSelects();

            return View(truckStatusDetails);
        }

        [HttpPost]
        public ActionResult Index(TruckStatusDetails truckStatusDetails)
        {
            try
            {
                int truckDetailsId = 0;

                //If TruckDetailsId is > 0 means here user wants to update existing Status Entry
                if (truckStatusDetails.TruckDetailsId <= 0)
                    truckDetailsId = this.prsService.CheckTruckStatusEntryExists(truckStatusDetails.TruckNumber);

                if (truckDetailsId > 0)
                {
                    truckStatusDetails.TruckDetailsId = truckDetailsId;

                    EditSelects();

                    return View(truckStatusDetails);
                }
                else
                {
                    truckStatusDetails.Createdby = Convert.ToString(Session["UserId"]);
                    truckStatusDetails.UpdatedBy = Convert.ToString(Session["UserId"]);
                    truckStatusDetails.Comments = string.IsNullOrEmpty(truckStatusDetails.Comments) ? string.Empty : truckStatusDetails.Comments;
                    truckStatusDetails.TransferStoreNo = truckStatusDetails.TransferStoreNo > 0 ? truckStatusDetails.TransferStoreNo : CurrentSiteInfo.SiteId;

                    if (truckStatusDetails.IsFleetTransfer == false)
                    {
                        truckStatusDetails.TransferValidFrom = null;
                        truckStatusDetails.TransferValidTo = null;
                    }
                    else if (truckStatusDetails.IsFleetTransfer == true && truckStatusDetails.IsTransferTemparory == false)
                    {
                        truckStatusDetails.TransferValidFrom = DateTime.Now;
                        truckStatusDetails.TransferValidTo = null;
                    }

                    this.prsService.SaveTruckStatusDetails(truckStatusDetails);

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                ModelState.AddModelError("error.error", ex.Message);

                EditSelects();

                return View(truckStatusDetails);
            }
        }

        public ActionResult List()
        {
            EditSelects();

            return View();
        }

        public ActionResult SearchTruckStatusList()
        {
            SearchFilter<TruckStatusFilterCriteria> tsSearchFilter = new SearchFilter<TruckStatusFilterCriteria>();
            tsSearchFilter.filter = new TruckStatusFilterCriteria();

            tsSearchFilter.rows = Convert.ToInt32(Request.Params["rows"]);
            tsSearchFilter.page = Convert.ToInt32(Request.Params["page"]);
            tsSearchFilter.sidx = Request.Params["sidx"];
            tsSearchFilter.sord = Request.Params["sord"];
            string filter = Request.Params["filter"];

            if (!string.IsNullOrEmpty(filter))
            {
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                tsSearchFilter.filter = serializer.Deserialize<TruckStatusFilterCriteria>(filter);
            }
            return GetTruckStatusDetailLst(tsSearchFilter);
        }

        private ActionResult GetTruckStatusDetailLst(SearchFilter<TruckStatusFilterCriteria> tsSearchFilter)
        {
            tsSearchFilter.filter.EnterdBy = Convert.ToString(Session["UserId"]);
            tsSearchFilter.filter.UpdatedBy = Convert.ToString(Session["UserId"]);

            var res = this.prsService.GetTruckStatusDetailList(tsSearchFilter);
            SearchResults<TruckStatusInfo> rtObj = new SearchResults<TruckStatusInfo>();
            rtObj.rows = res.ToList();
            rtObj.page = tsSearchFilter.page;

            int records = (rtObj.rows.Count() > 0 ? rtObj.rows[0].TotalRows : 0);
            float totPages = (records > 0 ? ((float)records / tsSearchFilter.rows) : 1);
            int totpages = (int)Math.Ceiling(totPages);
            rtObj.records = records;
            rtObj.total = totpages;
            rtObj.error = "";

            return this.Json(rtObj);
        }

        public ActionResult ExportTruckStatus(TruckStatusFilterCriteria filter)
        {
            SearchFilter<TruckStatusFilterCriteria> tsSearchFilter = new SearchFilter<TruckStatusFilterCriteria>();
            tsSearchFilter.filter = new TruckStatusFilterCriteria();
            tsSearchFilter.rows = 100000;
            tsSearchFilter.page = 1;
            tsSearchFilter.sidx = Request.Params["sidx"];
            tsSearchFilter.sord = Request.Params["sord"];

            if (filter != null)
            {
                tsSearchFilter.filter = filter;
                tsSearchFilter.sidx = filter.sidx;
                tsSearchFilter.sord = filter.sord;
            }

            var lstTS = this.prsService.GetTruckStatusDetailList(tsSearchFilter);

            DataGrid dg = new DataGrid();

            dg.DataSource = (from ts in lstTS
                             select new
                             {
                                 Facility = string.IsNullOrEmpty(ts.Facility) ? "" : ts.Facility,
                                 EntryDateDisp = string.IsNullOrEmpty(ts.EntryDateDisp) ? "" : ts.EntryDateDisp,
                                 EnterdBy = string.IsNullOrEmpty(ts.EnterdBy) ? "" : ts.EnterdBy,
                                 FleetID = string.IsNullOrEmpty(ts.FleetID) ? "" : ts.FleetID,
                                 Status = string.IsNullOrEmpty(ts.TruckStatus) ? "" : ts.TruckStatus,
                                 Comments = string.IsNullOrEmpty(ts.Comments) ? "" : ts.Comments
                             }).ToList();
            dg.DataBind();

            string attachment = "attachment;filename=FleetStatus_" + DateTime.Now.ToString("MMddyyy") + ".xls";

            Response.Clear();
            Response.Buffer = true;
            Response.ClearContent();
            Response.ClearHeaders();
            Response.Charset = "";

            StringWriter strwritter = new StringWriter();
            HtmlTextWriter htmltextwrtter = new HtmlTextWriter(strwritter);
            Response.Cache.SetCacheability(HttpCacheability.NoCache);

            Response.ContentType = "application/vnd.ms-excel";
            Response.AddHeader("Content-Disposition", attachment);

            dg.GridLines = GridLines.Both;
            dg.HeaderStyle.Font.Bold = true;
            dg.RenderControl(htmltextwrtter);

            Response.Write(strwritter.ToString());
            Response.End();

            return new EmptyResult();
        }

        private void EditSelects()
        {
            this.ViewBag.TruckStatuses = this.prsService.GetTruckStatus();
            this.ViewBag.TruckNumbers = this.prsService.GetTruckDetails(CurrentSiteInfo.GlobalSiteNum, DateTime.Now);
            this.ViewBag.AllFacilities = _userService.GetAllFacilities().Where(t => t.GlobalSiteNum != CurrentSiteInfo.GlobalSiteNum);

            DashboardSettings settings = DashboardSettings.RetrieveFromSession();
        }

        string UserFacilityName
        {
            get { return Convert.ToString(Session["FacilityName"]); }
        }

        #region Capacity Methods

        public ActionResult GetTempHourChange(string sidx, string sord, int page, int rows, int truckId, DateTime startDate, bool _search, string weekday)
        {
            try
            {
                int wkday = 0;
                int.TryParse(weekday, out wkday);
                var truckOpTempHoursRaw = this.prsService.GetTruckTempOpHourDetails(Convert.ToInt32(CurrentSiteInfo.GlobalSiteNum), startDate, rows, truckId, wkday);
                int totalCount = truckOpTempHoursRaw.Count();
                var truckOpTempHours = FilterGrid(truckOpTempHoursRaw, sidx, sord, page, rows);


                var pageSize = rows;
                var totalRecords = totalCount;
                var totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageSize);


                var jsonData = new
                {
                    total = totalPages,
                    page = page,
                    records = totalRecords,
                    rows = truckOpTempHours
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);

                var jsonData = new
                {
                    total = 0,
                    page = 0,
                    records = 0,
                    rows = new string[0]
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult SaveTempHourChange(FormCollection collection)
        {

Source/PRFacAppWF/Views/ApplicationSettings/Index.cshtml
@{
    ViewBag.Title = "Application Settings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/ApplicationSettings")
<script type="text/javascript">
    var URLHelper = {
        SearchTruckOpHoursUrl: '@Url.Action("SearchTruckOpHours", "TruckStatus")',
        GetApplicationSettingsListUrl: '@Url.Action("GetApplicationSettingsList", "ApplicationSettings")',
        SaveApplicationSettingsChange: '@Url.Content("/ApplicationSettings/UpdateApplicationSettingsRecords")',
        SearchApplicationSettingsUrl: '@Url.Action("SearchApplicationSettings", "ApplicationSettings")'
    };

    var isFullAccess = '@PRFacAppWF.Security.SecuredEntityDelegate.CanUserExecute(PRFacAppWF.Entities.Enums.ModuleName.ApplicationSettings, PRFacAppWF.Entities.Enums.AccessLevel.ReadAndWrite, true)';
</script>

<div class="child-body">
    <input id="hidSortDir" type="hidden" name="hidSortDir" value="DESC" />
    <input id="hidSortCol" type="hidden" name="hidSortCol" value="" />
    @using (Html.BeginForm("SearchApplicationSettings", "ApplicationSettings", null, System.Web.Mvc.FormMethod.Post, new { id = "SearchCorprateControlsFilterCriteria", onsubmit = "" }))
    {
        <div class="form-panel">
            <!--header image starts-->
            <h2>
                <span class="back-arrow">
                    <a href="/Dashboard.aspx">
                        <img src="/Images/back.png" width="48" height="48" style="float: left; margin-right: 10px;" />
                    </a>
                    <a href="/CorporateControls.aspx">
                        <img src="/Images/Previous.png" width="48" height="48" style="float: left; margin-right: 10px;" />
                    </a>
                </span>
                <img src="/Images/corporate-reports-icon.png" width="48" height="48" style="float: left; margin-right: 10px;" /><div class="h-title">
                    <span style="float: left; font-size: 9pt; text-transform: uppercase;">Corporate Controls</span><br />
                    <span style="float: left;">Application Settings</span>
                </div>
                <div class="nav-bar bg-color-none" style="float: right; width: auto; margin-top: 8px;">
                    <div class="nav-bar-inner new">
                    </div>
                </div>
                <div class="clearfix">
                </div>
            </h2>
            <!--<div class="show-map"><button class="image-button bg-color-grayDark fg-color-white">Show route map<img src="Images/map2.png" class="bg-color-blue"></button></div>-->
            <div class="clearfix"></div>
            <!--header image ends-->
            <!--pivot item starts -->
            <div class="metro-pivot touch-info-page corporate-controls">
                <div class="pivot-item">
                    <div class="bg-grey-newfilter">
                        <div class="tiltepanel">
                            <h4 class="title-h4">Search Application Settings</h4>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                        <ul class="form-list form-list-new" style="margin-top: 0%;">
                            <li class="width22prcnt">
                                <span class="label-form">Date</span>
                                <div clas="clearfix"></div>
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="text" value="@DateTime.Now.ToShortDateString()" name="StartDate" id="StartDate" readonly="readonly" title="Enter date to search records." style="margin-right: 0px; width: 80%;" />
                                        <img src="../Images/calendar-Icon.gif" id="StartDateIcon" />
                                    </div>
                                </span>
                            </li>
                            <li class="width24prcnt">
                                <div class="button-panel">
                                    <input type="submit" value="Search" title="Click to search." />
                                    <input type="submit" onclick="this.form.reset();" value="Reset" title="Click to reset page." />
                                    @if (PRFacAppWF.Security.SecuredEntityDelegate.CanUserExecute(PRFacAppWF.Entities.Enums.ModuleName.ApplicationSettings, PRFacAppWF.Entities.Enums.AccessLevel.ReadAndWrite, true))
                                    {
                                        <input type="submit" onclick='showApplicationSettingsPopup(-1); return false;' value="Add New Application Settings" title="Click here to add application settings." />
                                    }
                                    else
                                    {
                                        <input type="submit" disabled="disabled" onclick='showApplicationSettingsPopup(-1); return false;' value="Add New Application Settings" title="Click here to add application settings." />
                                    }
                                </div>
                            </li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>
                </div>
                <div class="clerfix"></div>
                <div style="width: 96%; margin: 0 auto; overflow-y: auto; height: 420px;" class="cust-grid-jqgrid">
                    @Html.Partial("~/Views/ApplicationSettings/partial/_listAS.cshtml")
                </div>
            </div>
            <div class="clerfix"></div>
        </div>
    }
</div>
<div id="popup" class="modal-box" style="width: 700px;">
    <header>
        <a href="#" class="js-modal-close close">×</a>
        <h3>Application Setting Details&nbsp;<span id="popupTruckOpHourHead"></span></h3>
    </header>
    <div class="modal-body">
        @Html.Partial("~/Views/ApplicationSettings/partial/_updateApplicationSettings.cshtml")
    </div>
    <footer>
        @if (PRFacAppWF.Security.SecuredEntityDelegate.CanUserExecute(PRFacAppWF.Entities.Enums.ModuleName.ApplicationSettings, PRFacAppWF.Entities.Enums.AccessLevel.ReadAndWrite, true))
        {
            <a href="#" id="modalUpdateselectedhours" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all">Add Application Setting</a>
        }
        else
        {
            <a href="#" id="modalUpdateselectedhours" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all not-active">Add Application Setting</a>
        }
        <a href="#" class="fm-button ui-state-default ui-corner-all js-modal-close">Close</a>
    </footer>
</div>