Source/PRFacAppWF/Controllers/TouchTimeController.cs
namespace PRFacAppWF.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using PRFacAppWF.CodeHelpers;
    using PRFacAppWF.models;
    using PRFacAppWF.Repository.Services;

    [HandleJsonExceptionAttribute]
    [Authorize]
    public class TouchTimeController : BaseController
    {
        private readonly IPRSService prsService;

        public TouchTimeController()
        {
            if (this.prsService == null)
                this.prsService = new PRSService();
        }

        public ActionResult Index()
        {
            ViewBag.FacilityList = this.prsService.GetFacilityListByUserId(CurrentUser.ID);
            return View();
        }

        public PartialViewResult SearchTouchTime(DateTime Date, string SortCol = null, string SortDir = null)
        {
            List<TouchTime> lstAS = new List<TouchTime>();
            try
            {
                SortCol = SortCol == "" ? "FacilityName" : SortCol;
                SortDir = SortDir == "" ? "ASC" : SortDir;
                lstAS = this.prsService.GetTouchTimeList(Date, CurrentUser.ID, SortCol, SortDir);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
            }

            return PartialView("partial/_listTouchTimeSearchResults", lstAS);
        }

        public ActionResult GetFacilityTouchTimeList(string sidx, string sord, int page, int rows, int FacilityId)
        {
            try
            {
                var varTouchTimeResults = this.prsService.SearchFacilityTouchTimeList(FacilityId);
                int totalCount = varTouchTimeResults.Count();
                var sortedResults = FilterTouchTimeGrid(varTouchTimeResults, sidx, sord, page, rows);
                
                var pageSize = 10;
                var totalRecords = totalCount;
                var totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageSize);
               
                var IsFullAccess = false;

                if (FacilityId > 0)
                    IsFullAccess = Security.SecuredEntityDelegate.CanUserExecute(Entities.Enums.ModuleName.TouchTime, Entities.Enums.AccessLevel.ReadAndWrite, Convert.ToString(FacilityId));
                else
                    IsFullAccess = Security.SecuredEntityDelegate.CanUserExecute(Entities.Enums.ModuleName.TouchTime, Entities.Enums.AccessLevel.ReadAndWrite, true);

                var jsonData = new
                {
                    total = totalPages,
                    page = page,
                    isfullaccess = IsFullAccess,
                    facilityId = FacilityId,
                    records = totalRecords,
                    rows = (from lst in sortedResults
                            select new
                            {
                                i = lst.CAPTouchtimeId,
                                cell = new string[]
                                {
                                    lst.CAPTouchtimeId.ToString(),
                                    lst.DE.ToString(),
                                    lst.DF.ToString(),
                                    lst.RE.ToString(),
                                    lst.RF.ToString(),
                                    lst.OBO.ToString(),
                                    lst.IBO.ToString(),
                                    lst.WA.ToString(),
                                    lst.CC.ToString(),
                                    lst.Startdate.HasValue ? lst.Startdate.Value.ToShortDateString():"",
                                    lst.Enddate.HasValue ? lst.Enddate.Value.ToShortDateString():"",                                    
                                    lst.State.ToString(),
                                    lst.FacilityId.ToString()
                                }
                            }).ToArray()
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);

                var jsonData = new
                {
                    total = 0,
                    page = 0,
                    records = 0,
                    rows = new string[0]
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
        }

        private IEnumerable<TouchTime> FilterTouchTimeGrid(IEnumerable<TouchTime> data, string sidx, string sord, int page, int rows)
        {

            int skiprows = (page - 1) * rows;
            ////Since in the UI we are displaying CapacityDate column as CapacityDateDisp.
            sidx = sidx == "" ? "Startdate" : sidx;
            if (sord == "desc")
                data = data.OrderByDescending(a => a.GetType().GetProperty(sidx).GetValue(a, null)).Skip(skiprows).Take(rows);
            else
                data = data.OrderBy(a => a.GetType().GetProperty(sidx).GetValue(a, null)).Skip(skiprows).Take(rows);

            return data;
        }

        public ActionResult UpdateTouchTimeRecords(int FacilityId)
        {
            ViewBag.FacilityId = FacilityId;
            return View();
        }

        [HttpPost]
        public JsonResult UpdateTouchTimeRecords(FormCollection formCollection)
        {
            DateTime? endDate = null;
            int DE = 0, DF = 0, RE = 0, RF = 0, OBO = 0, IBO = 0, WA = 0, CC = 0;
            bool isNullEnddate = false;
            string result = string.Empty;
            string errMsg = string.Empty;
            bool success = true;
            try
            {
                int facilityid = Convert.ToInt32(formCollection["hidfacilityid"]);
                DateTime startDate = Convert.ToDateTime(formCollection["Startdate"]);
                isNullEnddate = Convert.ToBoolean(formCollection["hidNullEndDate"]);
                if (!isNullEnddate)
                    endDate = Convert.ToDateTime(formCollection["Enddate"]);
                DE = Convert.ToInt32(Convert.ToDecimal(formCollection["DE"]));
                DF = Convert.ToInt32(Convert.ToDecimal(formCollection["DF"]));
                RE = Convert.ToInt32(Convert.ToDecimal(formCollection["RE"]));
                RF = Convert.ToInt32(Convert.ToDecimal(formCollection["RF"]));
                OBO = Convert.ToInt32(Convert.ToDecimal(formCollection["OBO"]));
                IBO = Convert.ToInt32(Convert.ToDecimal(formCollection["IBO"]));
                WA = Convert.ToInt32(Convert.ToDecimal(formCollection["WA"]));
                CC = Convert.ToInt32(Convert.ToDecimal(formCollection["CC"]));

                string lstAS = this.prsService.UpdateFacilityTouchTimeValues(CurrentUser.ID, facilityid, startDate, endDate, DE, DF, RE, RF, OBO, IBO, WA, CC, isNullEnddate);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                success = false;
                errMsg = ex.Message;
            }

            var retJSON = new
            {
                success = success,
                error = errMsg
            };
            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SetTouchtimetoCorporateDefault(FormCollection formCollection)
        {
            DateTime startDate = DateTime.Now;
            int facilityid = 0;
            string result = string.Empty;
            string errMsg = string.Empty;
            bool success = true;
            try
            {
                startDate = Convert.ToDateTime(formCollection["Startdate"]);
                facilityid = Convert.ToInt32(formCollection["hidfacilityid"]);
                string lstAS = this.prsService.SetTouchtimetoCorporateDefault(CurrentUser.ID, facilityid, startDate);
            }
            catch (Exception ex)
            {
                Helper.LogError(ex);
                success = false;
                errMsg = ex.Message;
            }

            var retJSON = new
            {
                success = success,
                error = errMsg
            };
            return Json(retJSON, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/PRFacAppWF/Views/TouchTime/Index.cshtml
@{
    ViewBag.Title = "Touch Time";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/TouchTime")
<script type="text/javascript">
    var URLHelper = {
        GetFacilityTouchTimeListUrl: '@Url.Action("GetFacilityTouchTimeList", "TouchTime")',
        SearchTouchTimeUrl: '@Url.Action("SearchTouchTime", "TouchTime")',
        SaveTouchTime: '@Url.Content("/TouchTime/UpdateTouchTimeRecords")',
        SetDefaultValueURL: '@Url.Content("/TouchTime/SetTouchtimetoCorporateDefault")',
    };
</script>

<div class="child-body">
    <input id="hidSortDir" type="hidden" name="hidSortDir" value="DESC" />
    <input id="hidSortCol" type="hidden" name="hidSortCol" value="" />
    @using (Html.BeginForm("SearchTouchTime", "TouchTime", null, System.Web.Mvc.FormMethod.Post, new { id = "SearchCorprateControlsFilterCriteria", onsubmit = "" }))
    {
        <div class="form-panel">
            <!--header image starts-->
            <h2>
                <span class="back-arrow">
                    <a href="/Dashboard.aspx">
                        <img src="/Images/back.png" width="48" height="48" style="float: left; margin-right: 10px;" />
                    </a>
                    <a href="/CorporateControls.aspx">
                        <img src="/Images/Previous.png" width="48" height="48" style="float: left; margin-right: 10px;" />
                    </a>
                </span>
                <img src="/Images/corporate-reports-icon.png" width="48" height="48" style="float: left; margin-right: 10px;" /><div class="h-title">
                    <span style="float: left; font-size: 9pt; text-transform: uppercase;">Corporate Controls</span><br />
                    <span style="float: left;">Touch Time</span>
                </div>
                <div class="nav-bar bg-color-none" style="float: right; width: auto; margin-top: 8px;">
                    <div class="nav-bar-inner new">
                    </div>
                </div>
                <div class="clearfix">
                </div>
            </h2>
            <!--<div class="show-map"><button class="image-button bg-color-grayDark fg-color-white">Show route map<img src="Images/map2.png" class="bg-color-blue"></button></div>-->
            <div class="clearfix"></div>
            <!--header image ends-->
            <!--pivot item starts -->
            <div class="metro-pivot touch-info-page corporate-controls">
                <div class="pivot-item">
                    <div class="bg-grey-newfilter">
                        <div class="tiltepanel">
                            <h4 class="title-h4">Search Touch Time</h4>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                        <ul class="form-list form-list-new" style="margin-top: 0%;">
                            <li class="width22prcnt">
                                <span class="label-form">Date</span>
                                <div clas="clearfix"></div>
                                <span class="value">
                                    <div class="input-control text">
                                        <input type="text" value="@DateTime.Now.ToShortDateString()" name="StartDate" id="StartDate" readonly="readonly" title="Enter date to search records." style="margin-right: 0px; width: 80%;" />
                                        <img src="../Images/calendar-Icon.gif" id="StartDateIcon" />
                                    </div>
                                </span>
                            </li>
                            <li class="width24prcnt">
                                <div class="button-panel">
                                    <input type="submit" value="Search" title="Click to search." />
                                    <input type="submit" onclick="this.form.reset();" value="Reset" title="Click to reset page." />
                                    @*@if (PRFacAppWF.Security.SecuredEntityDelegate.CanUserExecute(PRFacAppWF.Entities.Enums.ModuleName.TouchTime, PRFacAppWF.Entities.Enums.AccessLevel.ReadAndWrite))
                                        {*@
                                    <input type="submit" onclick='showTouchTimePopup(-1); return false;' value="Add Touch Time" title="Click here to add touch time." />
                                    @*}
                                        else
                                        {
                                            <input type="submit" onclick='showTouchTimePopup(-1); return false;' value="Add Touch Time" title="Click here to add touch time." disabled="disabled"/>
                                        }*@
                                </div>
                            </li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>

                </div>
                <div class="clerfix"></div>
                <div style="width: 96%; margin: 0 auto; overflow-y: auto; height: 420px;" class="cust-grid-jqgrid">
                    @Html.Partial("~/Views/TouchTime/partial/_listTouchTime.cshtml")
                </div>
            </div>
            <div class="clerfix"></div>
        </div>
    }
</div>
<div id="popup" class="modal-box">
    <header>
        <a href="#" class="js-modal-close close">×</a>
        <h3>Facility Touch Time Details&nbsp;<span id="popupTruckOpHourHead"></span></h3>
    </header>
    <div class="modal-body">
        @Html.Partial("~/Views/TouchTime/partial/_updateFacilityTouchTime.cshtml")
    </div>
    <footer>
        @*@if (PRFacAppWF.Security.SecuredEntityDelegate.CanUserExecute(PRFacAppWF.Entities.Enums.ModuleName.TouchTime, PRFacAppWF.Entities.Enums.AccessLevel.ReadAndWrite))
            {*@
        <a href="#" id="UpdateCorporateDefaults" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all" style="float:left;">Set to Corporate Default</a>
        <a href="#" id="modalUpdateselectedhours" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all">Add Touch Time</a>
        @*}
            else
            {
                <a href="#" id="UpdateCorporateDefaults" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all not-active" style="float:left;">Set to Corporate Default</a>
                <a href="#" id="modalUpdateselectedhours" class="js-modal-updateselectedhours fm-button ui-state-default ui-corner-all not-active">Add Touch Time</a>
            }*@
        <a href="#" class="fm-button ui-state-default ui-corner-all js-modal-close">Close</a>
    </footer>
</div>